import 'svelte'
//export * as Icon from './Icon/Icon.svelte'
export * from './[icon_name].svg/index.js'
export * from './markup/index.js'
export * from './markup_/index.js'
export * from './svg_preprocess_/index.js'
